# Generated by Django 3.2.8 on 2023-11-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=9, null=True)),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='nombre')),
                ('edad', models.IntegerField(max_length=2, null=True, verbose_name='edad')),
                ('asignaturas', models.CharField(max_length=100, null=True, verbose_name='asignaturas')),
                ('celular', models.IntegerField(max_length=9, verbose_name='celular')),
                ('apoderado', models.CharField(max_length=100, null=True, verbose_name='apoderado')),
            ],
        ),
    ]
