# Generated by Django 3.2.8 on 2023-11-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_auto_20231109_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='rut',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
