# Generated by Django 3.2.8 on 2023-11-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_alter_estudiante_rut'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='estudiante',
            new_name='alumno',
        ),
    ]
